spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/chocolate-factory?
        allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true&
        serverTimezone=UTC&characterEncoding=UTF-8&&useUnicode=true"
    username: root
    password: ''
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        #  sql:
        #    init:
        #      mode: always
  mvc:
    hidden-method:
      filter:
        enabled: true
example:
    app:
        jwtExpirationMs: 86400000
        jwtSecret: Top+Secret+Key+123456789Top+Secret+Key+123456789
logging:
  level:
    blog: WARN
    org: WARN
    org.hibernate.SQL: DEBUG
